---
# Source: spring-boot-app-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy-canary
  labels:
    app: spring-boot-api
spec:
  selector:
    matchLabels:
      app: spring-boot-api
  replicas: 3
  strategy:
    type: RollingUpdate #Parameterize?
  template:
    metadata:
      labels:
        app: spring-boot-api
        version: canary
      annotations:
        prometheus.io/path: '/api/actuator/prometheus'
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: spring-boot-app-api
          image: "samstest.azurecr.io/chakra:latest"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
            
          ports:
          - containerPort: 8080
            name: api
          - containerPort: 5005
            name: jvm-debug
          
          env:
          - name: SERVER_SERVLET_CONTEXT_PATH
            value: "/api"
          - name: spring.profiles.active
            value: "dev"
          imagePullSecrets:
          - name: regcred # Must be created and configured into kubectl